### ISSUE TITLE
HTTPS on your website

### ISSUE THREAD

**Issue by rugk** [kimai/roadmap#14]
You should add HTTPS to http://www.kimai.org/

Especially login fields are not liked e.g. by the latest version of Firefox and it will display a warning on http://demo.kimai.org/.
But anyway there is no argument against HTTPS.

Why you should always use HTTPS (no matter whether the site is static etc.):
* IT security specialist: https://scotthelme.co.uk/still-think-you-dont-need-https/
* Google: https://developers.google.com/web/fundamentals/security/encrypt-in-transit/why-https

**Comment by simonschaufi** [comment]
I think our website is hosted on github and github says:
https://help.github.com/articles/securing-your-github-pages-site-with-https/
> HTTPS is not supported for GitHub Pages using custom domains.

**Comment by rugk** [comment]
Hmm, but at least the demo page is hosted somewhere else.

**Comment by kevinpapst** [comment]
Added https to demo website
